name: Docker Build and Push Pipeline

on:
  push:
    branches: [ "main" ]

# FIX FOR WARNING: Purani Node.js warning ko bypass karne ke liye environment variable
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-ship:
    runs-on: ubuntu-latest

    steps:
      - name: Check out our repository code
        uses: actions/checkout@v4

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          # FIX FOR ERROR: Hum multi_stage_app folder ka rasta de rahe hain jahan asli Dockerfile hai
          context: ./multi_stage_app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lean-app:v1
